import riot from 'riot';
import $ from 'jquery';
import 'bootstrap';
import 'select2';
import 'froala-editor';
import 'blueimp/jQuery-File-Upload';
import 'nylen/shiftcheckbox';
import 'ilikenwf/nestedSortable';
import 'xdan/datetimepicker';
import 'moment/moment';

import 'tags/app.tag!';
import 'tags/login.tag!';
import 'tags/home.tag!';
import 'tags/nav-global.tag!';
import 'tags/nav-blog.tag!';
import 'tags/dashboard.tag!';
import 'tags/article/index.tag!';
import 'tags/article/create.tag!';
import 'tags/article/edit.tag!';
import 'tags/article/describe.tag!';
import 'tags/page/index.tag!';
import 'tags/page/create.tag!';
import 'tags/page/edit.tag!';
import 'tags/page/describe.tag!';
import 'tags/page/tree.tag!';
import 'tags/category/index.tag!';
import 'tags/tag/index.tag!';
import 'tags/customfield/index.tag!';
// import 'tags/customfield/create.tag!';
import 'tags/customfield/edit.tag!';
import 'tags/comment/index.tag!';
import 'tags/user/index.tag!';
import 'tags/user/edit.tag!';
import 'tags/user/describe.tag!';
import 'tags/user/invitation/index.tag!';
import 'tags/analytics/index.tag!';
import 'tags/analytics/edit.tag!';
import 'tags/system/index.tag!';
import 'tags/signup/signup.tag!';
import 'tags/froala.tag!';
// import 'tags/layout.tag!';
import 'tags/setup.tag!';

import 'tags/post-status-select2.tag!';

import 'froala-editor/js/plugins/align.min.js';
import 'froala-editor/js/plugins/char_counter.min.js';
import 'froala-editor/js/plugins/code_beautifier.min.js';
import 'froala-editor/js/plugins/code_view.min.js';
import 'froala-editor/js/plugins/colors.min.js';
import 'froala-editor/js/plugins/emoticons.min.js';
import 'froala-editor/js/plugins/entities.min.js';
import 'froala-editor/js/plugins/file.min.js';
import 'froala-editor/js/plugins/font_family.min.js';
import 'froala-editor/js/plugins/font_size.min.js';
import 'froala-editor/js/plugins/fullscreen.min.js';
import 'froala-editor/js/plugins/image.min.js';
import 'froala-editor/js/plugins/image_manager.min.js';
import 'froala-editor/js/plugins/inline_style.min.js';
import 'froala-editor/js/plugins/line_breaker.min.js';
import 'froala-editor/js/plugins/link.min.js';
import 'froala-editor/js/plugins/lists.min.js';
import 'froala-editor/js/plugins/paragraph_format.min.js';
import 'froala-editor/js/plugins/paragraph_style.min.js';
import 'froala-editor/js/plugins/quick_insert.min.js';
import 'froala-editor/js/plugins/quote.min.js';
import 'froala-editor/js/plugins/table.min.js';
import 'froala-editor/js/plugins/save.min.js';
import 'froala-editor/js/plugins/url.min.js';
import 'froala-editor/js/plugins/video.min.js';

import 'font-awesome/css/font-awesome.css!';
import 'froala-editor/css/froala_editor.min.css!';
import 'froala-editor/css/froala_style.min.css!';
import 'froala-editor/css/plugins/char_counter.min.css!';
import 'froala-editor/css/plugins/code_view.min.css!';
import 'froala-editor/css/plugins/colors.min.css!';
import 'froala-editor/css/plugins/emoticons.min.css!';
import 'froala-editor/css/plugins/file.min.css!';
import 'froala-editor/css/plugins/fullscreen.min.css!';
import 'froala-editor/css/plugins/image.min.css!';
import 'froala-editor/css/plugins/image_manager.min.css!';
import 'froala-editor/css/plugins/line_breaker.min.css!';
import 'froala-editor/css/plugins/quick_insert.min.css!';
import 'froala-editor/css/plugins/table.min.css!';
import 'froala-editor/css/plugins/video.min.css!';
import 'wallride/css/admin.css!';

riot.route.base('/_admin/');
riot.mount('app', {title:"Hello, JSPM and Riot!"});
riot.route.start(true);
